language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: u8iulpVs8TrDHHLtzl8TFBvXQIgvcEorp8E7TI8U17GqK214873lcBUdcPK3tokS/KSL5OedwyNPxpY65Iebu885qVcYmXML4f0497yjOj94H8OTEAdUAxB+DFR8J9fOXAu64tS0mYQCrB/Zyp9eFg3s8CmI6E9nBKxXTb9lzXbbpfLjNVcm++9YDOZhzFnbiw1Zw+EmXr+2NfV2hUTh/yiE1LUY8J9auVscq3jFbmNJoNFIwFK/B40OzaKhT/bkFixpLZiRdq2BkUH2j+JtGfFfYBSzOwG28fq/nfxlmuAUXkL9Ae/jgTnpukHdOwTgq2W8Zd9Pg3zBzv2CHpMZYHIDeuwpkH/JItU5XBlN/K7695evE1Lyi/GzG8vSDpkmtMyVnTIgQfv0O7bL7fxaiCY83Sa/OU3wrrU73we83FsIiudI4zY1c+o1HcBZ6BIFsIB4wFZYnYgT2uKwTtyZfbCi9jYJWDmY9qMDasBjPawGZixQpvEYJzyj8NQEWhhbaC45WT98b1DCnv/toJJ9XMAHFdbg1fdMu9I1vBjcqYjPQMhDcyQhLR7EO2S4pSb1GImd2WZPmWlbqcXQoLnxNPInjoZgBwZEDgv169y3mJNeE4g35rS7gqwXhT4mXHeQvIP5/UrOWSJ8W4GjW9/eIJOdPPD6GPi1tQd/1n6ggec=
  email: false
